TestDrivenDevelopment/hashthat-project/hashthat/urls.py
from django.contrib import admin
from django.urls import path
from hashingapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('hash/<str:id>/',views.hashview,name='hashview'),
    path('quickhash',views.quickhash, name='quickhash'),
]

TestDrivenDevelopment/hashthat-project/hashingapp/models.py
from django.db import models

# Create your models here.

class HashModel(models.Model):
    text=models.TextField()
    # Max length 64 since sha256 encoding always returns in 64 length output string
    hashed_text=models.CharField(max_length=64)

TestDrivenDevelopment/hashthat-project/hashingapp/forms.py
from django import forms

class HashForm(forms.Form):
    text=forms.CharField(label="Enter hash here: ", widget=forms.Textarea)

TestDrivenDevelopment/hashthat-project/hashingapp/views.py
from django.shortcuts import render,redirect
from .forms import HashForm
import hashlib
from .models import HashModel
import pdb
from django.http import JsonResponse

# Create your views here.

def home(request):
    if request.method=="POST":
        # Below we are sending the data to the HashForm(Basically request.POST contains the data)
        filled_form=HashForm(request.POST)
        if filled_form.is_valid():
            text=filled_form.cleaned_data['text']
            current_hashed_text=hashlib.sha256(text.encode('utf-8')).hexdigest()
            try:
                HashModel.objects.get(hashed_text=current_hashed_text)
            except HashModel.DoesNotExist:
                hashModel=HashModel()
                hashModel.text=text
                hashModel.hashed_text=current_hashed_text
                hashModel.save()
            return redirect('hashview',id=current_hashed_text)
    form = HashForm()
    return render(request,'hashingapp/home.html',{'form':form})

def hashview(request,id):
    hash_model_entry=None
    try:
        hash_model_entry=HashModel.objects.get(hashed_text=id)
    except HashModel.DoesNotExist:
        print("Inside doesnot exist")
        hash_model_entry={
            'message':"Url doesnot exist",
        }
    return render(request,'hashingapp/hashPage.html',{'hash_data':hash_model_entry})

def quickhash(request):
    text=request.GET['text']
    return JsonResponse({'hashed_text':hashlib.sha256(text.encode('utf-8')).hexdigest()})

TestDrivenDevelopment/hashthat-project/hashingapp/templates/hashingapp/hashPage.html
{% if hash_data.message %}
  <h1>{{hash_data.message}}</h1>
{% else %}
  <h2>Hash:</h2>
  <h1>{{hash_data.hashed_text}}</h1>
  <h2>Text:</h2>
  <h1>{{hash_data.text}}</h1>
{% endif %}
<h3>
  <a href="{% url 'home' %}">Home</a>
</h3>

TestDrivenDevelopment/hashthat-project/hashingapp/templates/hashingapp/home.html
<!-- action tells us where to go when the form is submitted -->
<form action="{% url 'home' %}" method="post">
  <!-- For method type post we require this csrf tag -->
  {% csrf_token %}
  <!-- as_p renders each of the form elements inside a p tag..Similarly we have as_ul, as_table etc in django -->
  {{form.as_p}}
  <!-- Value is the one which gets displayed visually -->
  <input type="submit" name="submit" value="Hash">
</form>

<h2 id='quickhash'></h2>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-- Keyup means this function gets executed when in this selected element a key stroke is generated -->
<script type="text/javascript">
  $('#id_text').keyup(function(){
    var text=$(this).val();
    $.ajax({
      url:'/quickhash',
      data:{
        'text':text
      },
      dataType:'json',
      success:function(data){
        $('#quickhash').text(data['hashed_text']);
      }
    });
  });
</script>